/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        outline: "#76777d",
        "on-error": "#ffffff",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary-container": "#7c839b",
        "on-secondary-fixed-variant": "#3323cc",
        "on-primary-fixed": "#131b2e",
        "on-background": "#0b1c30",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        surface: "#f8f9ff",
        "secondary-container": "#645efb",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#e2dfff",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#213145",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#009668",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed-dim": "#c3c0ff",
        "surface-variant": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        primary: "#000000",
        "inverse-primary": "#bec6e0",
        secondary: "#4b41e1",
        background: "#f8f9ff",
        tertiary: "#000000",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed-variant": "#005236",
        "outline-variant": "#c6c6cd",
        "on-secondary-container": "#fffbff",
        "tertiary-fixed": "#6ffbbe",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary-container": "#002113",
        "surface-tint": "#565e74",
        "primary-container": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0b1c30",
        "on-tertiary-fixed": "#002113",
        "surface-dim": "#cbdbf5",
        "on-surface-variant": "#45464d",
        "on-secondary-fixed": "#0f0069",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-lg": "1.5rem",
        gutter: "1.5rem",
        margin: "2rem",
        "gutter-sm": "1rem",
        "space-sm": "0.5rem",
        "margin-sm": "1rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "label-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        display: ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "data-mono": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        display: ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}